<!--
Copyright 2024 Google LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    https://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
-->
<template>
  <v-form
    v-model="valid"
    @submit.prevent="$emit('save', formData)"
    @keyup.enter="$emit('save', formData)"
  >
    <template v-for="field in fields" :key="field.name">
      <p>
        {{ field.description }}
      </p>
      <br />
      <component
        v-model="formData[field.name]"
        variant="outlined"
        color="primary"
        :is="getFieldComponent(field.type)"
        :label="field.label"
        :hint="field.label"
        :required="field.required"
        :rules="field.required ? [(v) => !!v || 'This field is required'] : []"
        :items="field.type === 'artifacts' ? artifactNames : field.items"
        :multiple="field.type === 'autocomplete' || 'artifacts'"
      />
    </template>
    <v-btn
      variant="text"
      color="info"
      class="text-none"
      @click="$emit('save', formData)"
      >Save</v-btn
    >
    <v-btn variant="text" class="text-none" @click="$emit('cancel')"
      >Cancel</v-btn
    >
  </v-form>
</template>

<script>
import { VTextField } from "vuetify/components/VTextField";
import { VTextarea } from "vuetify/components/VTextarea";
import { VCheckbox } from "vuetify/components/VCheckbox";
import { VRadio } from "vuetify/components/VRadio";
import { VSwitch } from "vuetify/components/VSwitch";
import { VSelect } from "vuetify/components/VSelect";
import { VAutocomplete } from "vuetify/components/VAutocomplete";

export default {
  props: {
    fields: {
      type: Array,
      required: true,
    },
  },
  components: {
    VTextField,
    VTextarea,
    VCheckbox,
    VRadio,
    VSwitch,
    VSelect,
    VAutocomplete,
  },
  data() {
    return {
      valid: false,
      // Initial form data.
      formData: this.fields.reduce((initialFormData, field) => {
        initialFormData[field.name] = field.value;
        return initialFormData;
      }, {}),
      // Artifact names from https://github.com/ForensicArtifacts/artifacts
      // TODO: Fetch these from the API instead and handle this in the API server.
      artifactNames: [
        "ApacheConfigurationFolder",
        "ApacheDefaultSiteConfigurationFile",
        "WordpressConfigFile",
        "ApacheAccessLogs",
        "MicrosoftIISLogs",
        "NginxErrorLogs",
        "ApacheErrorLogs",
        "NginxAccessLogs",
        "JavaCacheFiles",
        "KubernetesCertificates",
        "KubernetesKubeletPodManifest",
        "KubernetesKubeletPodLogs",
        "KubernetesLogs",
        "KubernetesClusterDatabase",
        "KubernetesKubeletConfiguration",
        "WindowsSiemensWinCCLogFile",
        "SignalDatabase",
        "SkypeUserProfile",
        "XChatLogs",
        "SkypeDb",
        "SignalApplicationContent",
        "SkypeChatSync",
        "SkypePreferences",
        "UnixLocalTimeConfigurationFile",
        "UnixGroupsFile",
        "UnixHostsFile",
        "CupsJobCacheFile",
        "UnixPasswdFile",
        "UnixUtmpFile",
        "UnixShadowFile",
        "UnixSudoersConfigurationFile",
        "UnixShadowBackupFile",
        "HAProxyLogFiles",
        "OsqueryLogFiles",
        "JenkinsLogFile",
        "ApacheKafkaLogFiles",
        "LinuxRsyslogConfigs",
        "HostAccessPolicyConfiguration",
        "LinuxLSBInit",
        "LinuxLocalTime",
        "PostgreSQLHistoryFile",
        "ThumbnailCacheFolder",
        "DebianPackagesLogFiles",
        "DebianVersion",
        "PythonHistoryFile",
        "FreeDesktopTrashFiles",
        "LinuxNssCachePasswdFile",
        "DebianPackagesStatus",
        "SecretsServiceDatabaseFile",
        "GnomeApplicationState",
        "RHostsFile",
        "LinuxLSBRelease",
        "LinuxKerberosConfiguration",
        "AnacronFiles",
        "SSHKnownHostsFiles",
        "LinuxSystemdJournalLogs",
        "LinuxGrubConfiguration",
        "LinuxWtmp",
        "LinuxSystemdOSRelease",
        "GTKRecentlyUsedDatabase",
        "LinuxDaemonLogFiles",
        "LinuxSysVInit",
        "NtpConfFile",
        "KernelModules",
        "Viminfo",
        "MySQLHistoryFile",
        "LinuxAuthLogs",
        "LessHistoryFile",
        "NetgroupConfiguration",
        "CronAtAllowDenyFiles",
        "FreeDesktopTrashInfoFiles",
        "LinuxDistributionRelease",
        "LinuxCronTabs",
        "DNSResolvConfFile",
        "AptitudeLogFiles",
        "LinuxHostnameFile",
        "LinuxPamConfigs",
        "SQLiteHistoryFile",
        "NanoHistoryFile",
        "LinuxFstab",
        "LinuxSystemdTimers",
        "LinuxSystemdJournalConfig",
        "LinuxPasswdFile",
        "LinuxInitrdFiles",
        "LinuxIssueFile",
        "SSHHostPubKeys",
        "LinuxSysctlConfigurationFiles",
        "LinuxNetworkManager",
        "UFWLogFile",
        "SSHAuthorizedKeysFiles",
        "UFWConfigFiles",
        "LinuxLoaderSystemPreloadFile",
        "WgetHSTSdatabase",
        "LocateDatabase",
        "LoginPolicyConfiguration",
        "LinuxSyslogNgConfigs",
        "ZeitgeistDatabase",
        "LinuxTimezoneFile",
        "YumSources",
        "LinuxDHCPConfigurationFile",
        "APTTrustKeys",
        "LinuxUdevRules",
        "SambaLogFiles",
        "LinuxSudoReplayLogs",
        "LinuxAtJobs",
        "LinuxCronLogs",
        "LinuxLastlogFile",
        "LinuxSysLogFiles",
        "LinuxUtmpFiles",
        "LinuxKernelLogFiles",
        "XDGAutostartEntries",
        "LinuxXinetd",
        "LinuxCACertificates",
        "LinuxAtJobsTemporaryOutputs",
        "GnomeTracker",
        "LinuxCACertificatesConfiguration",
        "LinuxDSDTTable",
        "LinuxMessagesLogFiles",
        "LinuxSystemdServices",
        "LinuxAuditLogs",
        "APTSources",
        "LinuxSSDTTables",
        "PCIDevicesInfoFiles",
        "LinuxIfUpDownScripts",
        "SshUserConfigFile",
        "JupyterConfigFile",
        "RedisConfigFile",
        "NfsExportsFile",
        "SshdConfigFile",
        "SambaConfigFile",
        "SafariTouchIconCacheSettingsSQLiteDatabaseFile",
        "ChromiumBasedBrowsersExtensions",
        "SafariAutoFillCorrectionsSQLiteDatabaseFile",
        "InternetExplorerHistory",
        "ChromeFileSystem",
        "FirefoxDownloads",
        "SafariHistorySQLiteDatabaseFile",
        "FirefoxHistory",
        "ChromiumBasedBrowsersWebDataDatabaseFile",
        "ChromePlatformNotifications",
        "FirefoxCookies",
        "SafariCookies",
        "WebKitPubSubSQLiteDatabaseFile",
        "FirefoxAddOns",
        "ChromiumBasedBrowsersFaviconsDatabaseFile",
        "SafariTabSnapshotsMetadataSQLiteDatabaseFile",
        "ChromiumBasedBrowsersExtensionActivitySQLiteDatabaseFile",
        "ChromePreferences",
        "FirefoxCache",
        "OperaHistoryFile",
        "SafariCacheSQLiteDatabaseFile",
        "SafariHistoryPlistFile",
        "SafariPerSitePreferencesSQLiteDatabaseFile",
        "ChromeSessionStorage",
        "SafariCloudAutoFillCorrectionsSQLiteDatabaseFile",
        "ChromeIndexedDB",
        "ChromiumBasedBrowsersCookiesDatabaseFile",
        "ChromiumBasedBrowsersHistoryDatabaseFile",
        "InternetExplorerCookies",
        "ChromiumBasedBrowsersLoginDataDatabaseFile",
        "ChromeLocalStorage",
        "InternetExplorerCache",
        "SafariDownloadsPlistFile",
        "ChromiumBasedBrowsersCache",
        "SafariFaviconsCacheSQLiteDatabaseFile",
        "SafariExtensions",
        "KornShellConfigurationFile",
        "ShellProfileFile",
        "FishShellConfigurationFile",
        "ZShellConfigurationFile",
        "TeeShellConfigurationFile",
        "ShellLogoutFile",
        "BashShellHistoryFile",
        "RootUserShellHistory",
        "CShellConfigurationFile",
        "BourneShellHistoryFile",
        "FishShellHistoryFile",
        "RootUserShellConfigs",
        "ZShellHistoryFile",
        "BashShellSessionFile",
        "BashShellConfigurationFile",
        "LinuxASLREnabled",
        "LinuxRestrictedDmesgReadPrivileges",
        "LinuxNetworkPathFilteringSettings",
        "LinuxProcMounts",
        "LinuxRestrictedKernelPointerReadPrivileges",
        "LinuxProcArp",
        "LinuxNetworkIpForwardingState",
        "LinuxIgnoreICMPBroadcasts",
        "LinuxSecureFsLinks",
        "LinuxSyncookieState",
        "LinuxKernelModuleRestrictions",
        "LinuxSecureSuidCoreDumps",
        "LinuxKernelModuleTaintStatus",
        "LinuxNetworkRedirectState",
        "LinuxKernelBootloader",
        "ContainerdConfig",
        "ContainerdLogs",
        "LinuxRelease",
        "NTFSMFTFiles",
        "NTFSLogFile",
        "NTFSUSNJournal",
        "DropboxClient",
        "GoogleDriveClient",
        "SkyDriveClient",
        "WindowsCortanaDatabase",
        "WindowsUpdateStoreDatabaseFile",
        "WindowsApplicationCompatibilityInstalledShimDatabases",
        "WindowsSecuritySettingsDatabases",
        "WindowsSystemRegistryFiles",
        "WindowsTempDirectories",
        "WindowsWebCacheStorageQuotaDatabaseFile",
        "WindowsEventLogApplication",
        "WindowsRecycleBinMetadata",
        "WindowsRecentFileCacheBCF",
        "WindowsRecycleBin",
        "WindowsUserRegistryTransactionLogFiles",
        "WindowsPowerShellHistory",
        "WindowsSuperFetchFiles",
        "WindowsXMLEventLogApplication",
        "WindowsBootConfigurationDataRegistryFiles",
        "WindowsXMLEventLogSystem",
        "WindowsPrefetchFiles",
        "WindowsMetroApplicationCookies",
        "WindowsEventLogSystem",
        "WindowsPowerShellDefaultProfiles",
        "WindowsStartupFolders",
        "WindowsEventLogSecurity",
        "WindowsUserAccessLogging",
        "WindowsXMLEventLogSysmon",
        "WindowsUserRegistryFiles",
        "WindowsCIMRepositoryFiles",
        "WindowsBITSQueueManagerDatabases",
        "WindowsSystemRegistryTransactionLogFilesBackup",
        "WindowsActiveDirectoryDatabase",
        "WindowsXMLEventLogTerminalServices",
        "WindowsUserRecentFiles",
        "WindowsUpdateLogFile",
        "WindowsUserAutomaticDestinationsJumpLists",
        "WindowsCrashDumps",
        "WindowsUpdateCatalogDatabaseFile",
        "WindowsUpdateDataStoreDatabaseFile",
        "WindowsSearchDatabase",
        "WindowsUserCustomDestinationsJumpLists",
        "WindowsActivitiesCacheDatabase",
        "WindowsRoverAutostartDLL",
        "WindowsXMLEventLogSecurity",
        "WindowsScheduledTasks",
        "WindowsStateRepositoryDeploymentDatabaseFile",
        "WindowsCryptnetUrlCacheMetadata",
        "WindowsSetupApiLogs",
        "WindowsSystemRegistryFilesBackup",
        "WindowsAMCacheHveFile",
        "WindowsFirewallLogFile",
        "WindowsAutoexecBat",
        "WindowsCommonFilePlacementAttacks",
        "WindowsGroupPolicyScripts",
        "WindowsHotkeyReplacement",
        "WindowsSystemResourceUsageMonitorDatabaseFile",
        "WindowsSmsRouterInterceptStoreDatabaseFile",
        "WindowsAppXRT",
        "WindowsMetroApplicationCache",
        "WindowsPushNotificationDatabaseFile",
        "WindowsStateRepositoryMachineDatabaseFile",
        "WindowsEventLogs",
        "WindowsCryptnetUrlCacheContent",
        "WindowsMetroApplicationHistory",
        "WindowsRDPClientBitmapCache",
        "WindowsConfigSys",
        "WindowsWinstart",
        "WindowsHostsFiles",
        "WindowsSystemIniFiles",
        "WindowsAutorun",
        "WindowsStartupInfo",
        "WindowsEventTracingLogFiles",
        "WindowsMetroUserPinnedFavoriteTiles",
        "WindowsSystemRegistryTransactionLogFiles",
        "WindowsTileDataLayerDatabase",
        "GKEDockerContainerLogs",
        "DockerContainerConfig",
        "ESXApiForwarder",
        "ESXiTrustedInfrastructureAgentLog",
        "ESXiAuthenticationLog",
        "ESXiHostAgentLog",
        "ESXiVMKernelWarningsLog",
        "vSphereClientLogsDirectory",
        "ESXiAttestationService",
        "ESXiVMKernelLog",
        "ESXiKeyProviderService",
        "vCenterServerAgentLog",
        "ESXiSystemMessageslog",
        "ESXiQuickBootLog",
        "ESXiVMKernelSummaryLog",
        "ESXiShellLog",
        "ESXTokenService",
        "ESXiSystemLogsDirectory",
        "HadoopYarnLogs",
        "HadoopAppRoot",
        "HadoopAppLogs",
        "DLLHijackLocations",
        "SophosAVLogs",
        "MicrosoftAVQuarantine",
        "WindowsDefenderScanDetectionHistoryFiles",
        "SymantecAVLogs",
        "SymantecAVQuarantine",
        "CrowdstrikeAgentID",
        "EsetAVQuarantine",
        "SophosAVQuarantine",
        "CrowdstrikeQuarantine",
        "MicrosoftAVLogs",
        "Bit9LocalCache",
        "SantaLogs",
        "PythonWheelInfo",
        "PythonDistInfo",
        "PythonEggInfo",
        "RubyGems",
        "TomcatLogFiles",
        "TomcatPasswordFile",
        "MicrosoftOutlookPSTFiles",
        "MicrosoftSqlServerErrorLogs",
        "MicrosoftOutlookOSTFiles",
        "MicrosoftOfficeMRU",
        "MozillaThunderbird",
        "GnomeEvolution",
        "NodeJSPackageManagerCacheFiles",
        "MicrosoftOfficeAutosave",
        "MicrosoftOutlookPABFiles",
        "KasperskyCaretoWindowsFile",
        "KasperskyCaretoDarwinFile",
        "MySQLDataDictionary",
        "MySQLConfigurationFiles",
        "ElasticsearchAccessLog",
        "ElasticsearchAuditLog",
        "PostgreSQLLogFiles",
        "PostgreSQLConfigurationFiles",
        "ElasticsearchLogs",
        "MongoDBLogFiles",
        "ElasticsearchServerLog",
        "MySQLDataDirectory",
        "MongoDBDatabasePath",
        "RedisConfigurationFile",
        "MySQLLogFiles",
        "MongoDBConfigurationFile",
        "ElasticsearchGCLog",
        "OpenSearchLogFiles",
        "RedisDataDirectory",
        "PostgreSQLDataDirectory",
        "RedisLogFiles",
        "MacOSMailSignatures",
        "MacOSNotesSQLiteDatabaseFile",
        "MacOSCallHistoryCacheSQLiteDatabaseFile",
        "MacOSCoreAnalyticsFile",
        "MacOSLogFile",
        "MacOSLastlogFile",
        "MacOSUserLocalItemsKeychainKeybagSQLiteDatabaseFile",
        "MacOSiOSBackupInfo",
        "MacOSPeriodicSystemFunctionConfigurationFile",
        "MacOSRemoteDesktopAdministratorSystem",
        "MacOSTimeMachinePlistFile",
        "MacOSContentsInfoPlistFile",
        "MacOSKeyboardLayoutPlistFile",
        "MacOSUserDockDesktopPictureSQLiteDatabaseFile",
        "MacOSiOSBackupManifest",
        "MacOSDuetKnowledgeCSQLiteDatabaseFile",
        "MacOSUserTrashDirectory",
        "MacOSSoftwareUpdatePreferencesPlistFile",
        "MacOSUserGlobalPreferencesPlistFile",
        "MacOSIdentityServicesSQLiteDatabaseFile",
        "MacOSApplicationResourcesStringsPlistFile",
        "MacOSNetworkUsageSQLiteDatabaseFile",
        "MacOSLoginWindowPlistFile",
        "MacOSUserPreferencesDirectory",
        "MacOSMailEnvelopIndex",
        "MacOSSwapFile",
        "MacOSStartupItemsPlistFile",
        "MacOSMailIMAP",
        "MacOSCodeSignatureCodeResourcesPlistFile",
        "MacOSDuetSQLiteDatabaseFile",
        "MacOSAssetCacheInfoSQLiteDatabaseFile",
        "MacOSUnifiedLogging",
        "MacOSDuetSystemEventsSQLiteDatabaseFile",
        "MacOSSystemVersionPlistFile",
        "MacOSNotificationCenterSQLiteDatabaseFile",
        "MacOSUserKeychainFile",
        "MacOSResourcesInfoStringsPlistFile",
        "MacOSSystemConfigurationPreferencesPlistFile",
        "MacOSResourcesLocalizableStringsPlistFile",
        "MacOSMailOpenedAttachments",
        "MacOSAuthorizationRulesSQLiteDatabaseFile",
        "MacOSUserLocalItemsKeychainRecordsSQLiteDatabaseFile",
        "MacOSiOSBackupMbdb",
        "MacOSAppleSetupDoneFile",
        "MacOSGlobalPreferencesPlistFile",
        "MacOSKernelExtensionFile",
        "MacOSLaunchDaemonsPlistFile",
        "MacOSMailDownloadAttachments",
        "MacOSSpotlightStoreVolumeConfigurationPlistFile",
        "MacOSSiriSuggestionsPendingQueueSQLiteDatabaseFile",
        "MacOSApplePushServiceSQLiteDatabaseFile",
        "MacOSSiriAnalyticsSQLiteDatabaseFile",
        "MacOSTCCSQLiteDatabaseFile",
        "MacOSUserKeychainOCSPCacheSQLiteDatabaseFile",
        "MacOSDirectoryServicesLocalNodesSQLiteDatabaseFile",
        "MacOSXcodeiOSDeviceLogsSQLiteDatabaseFile",
        "MacOSAppleSystemLogFile",
        "MacOSMailBackupTOC",
        "MacOSAirportPreferencesPlistFile",
        "MacOSLaunchAgentsPlistFile",
        "MacOSDockConfigurationPlistFile",
        "MacOSRemoteDesktopClientSystem",
        "MacOSApplicationsRecentItems",
        "MacOSCalendarCacheSQLiteDatabaseFile",
        "MacOSMailAccounts",
        "MacOSMailMainDirectory",
        "MacOSDuetActivitySchedulerSQLiteDatabaseFile",
        "MacOSUserPasswordHashesPlistFile",
        "MacOSUtmpxFile",
        "MacOSSidebarListsPlistFile",
        "MacOSiOSBackupsMainDirectory",
        "MacOSRecentItemsPlistFile",
        "MacOSSiriSuggestionsEntitiesSQLiteDatabaseFile",
        "MacOSTextReplacementsSQLiteDatabaseFile",
        "MacOSContentsVersionPlistFile",
        "MacOSiDevices",
        "MacOSFSEventsFile",
        "MacOSWirelessDiagnosticDataPersistentSQLiteDatabaseFile",
        "MacOSMailboxes",
        "MacOSSystemPreferencesPlistFile",
        "MacOSiTunesInterfaceBuilderDocumentPlistFile",
        "MacOSSystemLogFile",
        "MacOSSpotlightVolumeConfigurationPlistFile",
        "MacOSSystemPolicySQLiteDatabaseFile",
        "MacOSAtJobs",
        "MacOSCronTabs",
        "MacOSMailPOP",
        "MacOSQuarantineEventsSQLiteDatabaseFile",
        "MacOSiCloudPreferences",
        "MacOSApplicationBundleCacheSQLiteDatabaseFile",
        "MacOSAddressBookImagesSQLiteDatabaseFile",
        "MacOSDuetinteractionCSQLiteDatabaseFile",
        "MacOSiOSBackupStatus",
        "MacOSInstallationHistoryPlistFile",
        "MacOSGatekeeperOpaqueConfigurationSQLiteDatabaseFile",
        "MacOSMailRecentContacts",
        "MacOSUserLoginItemsPlistFile",
        "MacOSiCloudAccounts",
        "MacOSSiriSuggestionsSnippetsSQLiteDatabaseFile",
        "MacOSSleepimageFile",
        "MacOSInstallationLogFile",
        "MacOSUserApplicationLogFile",
        "MacOSBluetoothPlistFile",
        "MacOSWalletSQLiteDatabaseFile",
        "MacOSMailPreferences",
        "MacOSUserAccountsSQLiteDatabaseFile",
        "MacOSAuditLogFile",
        "MacOSMessageChatSQLiteDatabaseFile",
      ],
    };
  },
  methods: {
    getFieldComponent(type) {
      // Map field types to Vuetify components
      const mapping = {
        text: "v-text-field",
        textarea: "v-textarea",
        checkbox: "v-checkbox",
        radio: "v-radio",
        switch: "v-switch",
        select: "v-select",
        autocomplete: "v-autocomplete",
        artifacts: "v-autocomplete",
      };
      return mapping[type] || "v-text-field"; // Default to text field
    },
  },
};
</script>

<style scoped></style>
